version: '3.8'

services:
  bert-sentiment-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bert-sentiment-app
    image: bert-sentiment-app:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - TRANSFORMERS_CACHE=/app/model_cache
    volumes:
      - model_cache:/app/model_cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sentiment-network

volumes:
  model_cache:
    driver: local

networks:
  sentiment-network:
    driver: bridge
