apiVersion: v1
kind: Service
metadata:
  name: bert-sentiment-app-service
  namespace: default
  labels:
    app: bert-sentiment-app
spec:
  type: NodePort
  selector:
    app: bert-sentiment-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30007
